default_platform(:ios)

platform :ios do
  desc "Build and upload the app to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      in_house: false
    )

    build_app(
      scheme: "ScarletViolet-Pokedex-SwiftUI", # Update if your scheme name differs.
      export_method: "app-store"
      # Provide either `workspace: "ScarletViolet-Pokedex-SwiftUI.xcworkspace"` or
      # `project: "ScarletViolet-Pokedex-SwiftUI.xcodeproj"` if fastlane cannot infer it automatically.
    )

    upload_to_testflight
  end
end
